### ISSUE TITLE
question + localizing

### ISSUE THREAD

**Issue by eloib** [ScottHamper/chatsuey#2]
I can help localize in mandarin and french if needed

**Comment by ScottHamper** [comment]
Oh man, that would be so awesome, Eloi!

Here's a list of the addons that have strings to localize:
- ChatSuey
- ChatSuey-FontSettings
- ChatSuey-MiniChannels
- ChatSuey-Timestamps
- ChatSuey-WebLinks

Each of these addons have an `i18n` folder with an `enUS.lua` file inside of them. To localize for French/Chinese, take the following steps:

1. Copy `enUS.lua` and rename it to `frFR.lua` (for French). For Chinese, there seems to be two possible options:
  - `zhCN`: Chinese (China) (simplified) implemented LTR left-to-right in WoW
  - `zhTW`: Chinese (Taiwan) (traditional) implemented LTR left-to-right in WoW
  - Source: http://wowwiki.wikia.com/wiki/API_GetLocale
2. Open up the newly created file in your editor of choice.
3. Replace appropriate strings (I'll provide some more detail on this in a second).
4. In the addon's root directory, update the `.toc` file to include a reference to the new file, e.g., `i18n\frFR.lua` (put it underneath the reference to the `i18n\enUS.lua` file).

When it comes to replacing strings, most of the addons will be fairly straight forward. For example, the ChatSuey-WebLinks `frFR.lua` file might look something like:

```
local LS = _G.ChatSuey.Locales["frFR"].Strings;

LS["Copy the URL into your clipboard (Ctrl-C):"] = "FRENCH TRANSLATION HERE";
```

Note that the first line needed to have its locale string changed to "frFR", and that the left-side of each text string should remain in its original English form. Only the right-side should be changed to the appropriate translation.

The only addon that will be slightly different is the base `ChatSuey` addon. The locale file for this one is a little bit more complicated at the very start of the file. For example, for French, the beginning might look like:

```
local _G = getfenv();
local ChatSuey = _G.ChatSuey;
local frFR = ChatSuey.Locale:new();
local LS = frFR.Strings;

ChatSuey.Locales = ChatSuey.Locales or ChatSuey.LocaleTable:new(frFR);
ChatSuey.Locales["frFR"] = frFR;
```

Although there's more "stuff" here, all that really needed to happen was to replace any occurrence of "enUS" with "frFR".

Once you've added references to the new file in each addon's `.toc` file, the translations should automatically start appearing in-game as long as you use a French/Chinese game client.

I hope all of this makes sense and doesn't seem too daunting! I think you'll find once you start getting into it that it will go pretty quickly. Of course, if you run into any snags or get confused by anything, absolutely let me know - I want to make this as easy for you as possible.

I really really appreciate your offer to help localize the addon! It's very exciting, :). Thanks so much for checking out ChatSuey.

**Comment by eloib** [comment]
Thank you very much, I will get working on it, but before that I would like to let you know that after installing the latest version, I get an UI error upon launching the game on all clients
[img]http://i.imgur.com/zSI5fSx.png[/img]

**Comment by ScottHamper** [comment]
Whoops! Thanks for pointing this out - it should be fixed in the master branch now.

**Comment by eloib** [comment]
[ChatSueylocalized001.zip](https://github.com/ScottHamper/ChatSuey/files/601296/ChatSueylocalized001.zip)

I am done with the translating, but unfortunately there appears to be some problem with the language selection based on client. 



I don't know if I messed something up but after some testing, it appears to me that the last localization .lua file listed in the .toc files just gets picked automatically. 
For instance, if in ChatSuey-WebLinks.toc , i put the files in this order
```
i18n\enUS.lua
i18n\frFR.lua
i18n\zhCN.lua

Main.lua
```
then the weblink addon will be in chinese, because it's listed last. When I  changed the last .lua files on 3 different chatsuey addons .toc I ended up with a different language for each chatsuey function in game

2 other things:
I dont think there is a zhTW vanilla client, or at least I have never seen one
Chinese characters cannot be shortened so this probably shouldnt be localized

In the end the addon works perfectly without localization so I believe this is a very low priority task!

**Comment by ScottHamper** [comment]
THANK YOU SO MUCH, Eloi!

This is so awesome - I can't tell you how excited I am to receive your help in adding these translations.

I believe I've fixed the bug with locales overriding one another in the master branch, so go ahead and give it a try when you have some time. I've also merged in the translations you've provided with just one small change - I updated the "Chef de Raid" MiniChannel abbreviation to just "CR" instead of "CdR" to be consistent with the other abbreviations (e.g., "AR" for "Avertissement de Raid"). Let me know if this seems reasonable to you.

With regards to the MiniChannels addon and Chinese - while the party/guild/etc channels cannot be abbreviated in Chinese, does the addon still provide value for trade/general/etc channels? In English, these channels go from like `[1. General]` to `[1]`. If this is still useful behavior for Chinese players, would you be able to add a `zhCN.lua` file that simply sets the party/guild/etc "abbreviation" to the original/full character(s) of the channel names? That way, those channel labels won't change to English when Chinese players have the addon enabled. However, if you think this addon would never be enabled by Chinese players, then there's no reason to add a locale file for them. I hope this makes sense!

Lastly, would you be able to provide translations for all the strings in `ChatSuey\i18n\frFR.lua` and `ChatSuey\i18n\zhCN.lua`? These strings are used for referencing colors in some of the other addons (e.g., in the MarkdownLinks addon). They should be fully capitalized (I imagine this is not relevant for Chinese), and contain no space characters.

I think these are the only remaining edits, and then the localizations will be good to go! Thanks again for all your help - I really appreciate it.

**Comment by ScottHamper** [comment]
Hey @eloib ,

Is there any chance I can get your help on these last couple items? I'd like to add a big "thank you" to the README for your work, and package up a new official release with all these changes included. However, I'd like to have the localization completely finished up before doing so. I'd be very grateful if you can spare me a bit more of your time!

**Comment by eloib** [comment]
Hey，
sorry I have been out of wow for a while
I have created 2 pull requests with the translations of the localization files,
about the minichannels in chinese:
General channel is : [1. 综合]
Trade : [2. 交易]
General defense: [3. 本地防务]
guild: [公会]

**Comment by ScottHamper** [comment]
Wooo! Thanks again for all your time, @eloib - this is perfect. I'm going to prepare a new release!

**Comment by Nihlo** [comment]
![wowscrnshot_110517_014717](https://user-images.githubusercontent.com/26931653/32410873-5bcd61c2-c1cb-11e7-8174-7cc01be568a7.jpg)
Hey, thanks a lot for your addons. Get a small error on login though
