### ISSUE TITLE
Chat dropdown menu doesnt work with Stubby

### ISSUE THREAD

**Issue by Daimie** [ScottHamper/chatsuey#3]
The following error shows when trying to right-click a chat menu while Stubby addon (which is required for several important addons such as Auctioneer, Informant, Enchantrix) is enabled:

Error: Interface\FrameXML\UIDropDownMenu.lua:182: attempt to index local `info' (a nil value)

**Comment by ScottHamper** [comment]
Steps to reproduce:

1. Install Auctioneer and its dependencies (EnhTooltip, Stubby) from [this repo](https://github.com/ericraio/vanilla-wow-addons).
2. Enable ChatSuey and ChatSuey-FontSettings.
3. Right-click a chat frame tab.

Error does not occur with Informant/Enchantrix installed, only Auctioneer.

**Comment by ScottHamper** [comment]
It looks like [ChatSuey's hook for `UIDropDownMenu_AddButton`](https://github.com/ScottHamper/chatsuey/blob/master/ChatSuey/UIDropDownMenu.lua#L11) is being wiped out somewhere. Once Auctioneer has finished loading, ChatSuey's hook method never gets called again. Annoyingly, it is not obvious where Auctioneer is overwriting the method (though realistically, it probably doesn't matter - it's not like vanilla Auctioneer is going to get patched).

One simple solution is to add Auctioneer as an optional dependency for ChatSuey in order to force ChatSuey to load after Auctioneer. This allows ChatSuey to hook the `UIDropDownMenu_AddButton` method only after whatever code in Auctioneer would otherwise wipe the hook out. I'm really not a fan of this solution, as it's ultimately working around a bug/poor coding in Auctioneer - Auctioneer is being a "bad tenant" and should ideally be patched to play nice with other addons. However, it seems apparent that this will never happen.
